version: '3'
services:
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysqldb

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    ports:
     - 8181:80
    environment:
      - PMA_ARBITRARY=1

  java-app:
    image: app:1.3-arm64
    ports:
      - 8080:8080
    environment:
      - DB_NAME=${DB_NAME}
      - DB_SERVER=${DB_SERVER}
      - DB_PWD=${DB_PWD}
      - DB_USER=${DB_USER}
    depends_on:
      - mysqldb

volumes:
  mysql-data:
    driver: local